config/routes.rb
Rails.application.routes.draw do

  resources :submissions
  root 'home#index'
  post 'login' => 'sessions#create'
  post 'signup' => 'users#create'

  get 'all_subject_info' => 'subjects#all_subject_info'
  get 'all_subject_names' => 'subjects#all_subject_names'

  resources :users
  resources :subjects
  resources :groups

  get 'leaderboard' => 'submissions#leaderboard'

  post 'reset_password/request_token' => 'reset_password#request_token'
  post 'reset_password/update_password/:verification_token' => 'reset_password#update_password'

  delete 'destroy_assessment' => 'assessments#destroy'
  put 'update_comments' => 'assessments#update_comments'
end

app/models/submission.rb
class Submission < ApplicationRecord
  include ActionView::Helpers::DateHelper
  belongs_to :user

  has_many :assessments

  validates :score, presence: true

  attr_accessor :submitted_by

  def submitted_by
    puts "#{self.user.inspect}"
    self.user.slice(:name, :email)
  end

  def as_json(options = {})
    h = super(options, [:created_at])
    h[:submitted_by] = submitted_by
    puts "The record is : #{h}"
    puts "The created at value is : #{h['created_at']}"
    h[:submission_time] = time_ago_in_words(h['created_at']) + ' ago'
    h.delete('created_at')
    h
  end

end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  # before_action :set_submission, only: [:show, :edit, :update, :destroy]

  def index
    submissions = Submission.where(user: @current_user)
    render json: submissions.as_json, status: :ok
  end

  def create
    submission = Submission.new(submission_params)
    submission.user = @current_user
    if submission.valid? && submission.save
      render json: submission.as_json, status: :created
    else
      render json: { errors: submission.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def leaderboard
    groups = Group.all
    groups = groups.select {|group| !group.best_submission.nil?}
    groups = groups.sort_by {|group| -group.best_submission.score}

    render json: groups.as_json.each_with_index { |record, index| record[:rank] = index+1}, status: :ok
  end


  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_submission
      @submission = Submission.find(params[:id])
    end

  def submission_params
    params.require(:submission).permit(:score)
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/_form.html.erb
<%= form_with(model: submission, local: true) do |form| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Submissions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Submission', new_submission_path %>

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>